version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 3006:3006
    command: bundle exec rails s -p 3006 -b 0.0.0.0
    volumes:
      - ./:/app:cached
    stdin_open: true
    tty: true     